
import aktion from './aktionariat.jpg'
import alice from './alice.jpg'
import alphawallet from './alphawallet.jpg'
import argent from './Argent.jpg'
import atwallet from './at.wallet.jpg'
import atomic from './atomic.jpg'
import authereum from './authereum.jpg'
import bash from './bash.jpg'
import binance from './Binance.jpg'
import bitkeep from './bitkeep.jpg'
import bitpay from './bitpay.jpg'
import bridgewallet from './bridgewallet.jpg'
import btc from './btc.png'
import coin98 from './coin98.jpg'
import coinbase from './coinbase.png'
import coinomi from './coinomi.jpg'
import coolwallet from './coolWallet.jpg'
import cybavowallet from './cybavowallet.jpg'
import dcentwallet from './dcentwallet.jpg'
import defiant from './defiant.jpg'
import dharna from './dharna.jpg'
import dokwallet from './dokwallet.jpg'
import easypocket from './easypocket.jpg'
import eidoo from './eidoo.jpg'
import ellipal from './ellipal.jpg'
import equal from './Equal.jpg'
import facebook from './facebook-brands.svg'
import flarwalle from './flarwalle.jpg'
import github from './github-brands.svg'
import gnosis from './gnosis.jpg'
import gridplus from './GridPlus.jpg'
import guardwallet from './guardwallet.jpg'
import halodefi from './halodefi.jpg'
import hashkeyme from './hashkeyme.jpg'
import huobiWallet from './huobiWallet.jpg'
import i from './i.jpg'
import inchwallet from './inchwallet.jpg'
import infinity from './infinitywallet.jpg'
import infinyo from './infinyo.jpg'
import jadewallet from './jadewallet.jpg'
import keyring from './keyring.jpg'
import kyberswap from './kyberswap.jpg'
import ledgerlive from './ledgerlive.jpg'
import logo from './logo.png'
import loopring from './loopring.jpg'
import mathwallet from './mathwallet.jpg'
import meet from './meet.jpg'
import metamask from './MetaMask.jpg'
import midas from './midasWallet.jpg'
import morix from './morix.wallet.jpg'
import mykey from './MYKEY.jpg'
import o3Wallet from './o3Wallet.jpg'
import onto from './ONTO.jpg'
import ownbit from './ownbit.jpg'
import peakdefiwallet from './peakdefiwallet.jpg'
import Pillar from './Pillar.jpg'
import plasmapay from './plasmapay.jpg'
import Rainbow from './Rainbow.jpg'
import Rwallet from './Rwallet.jpg'
import Safepal from './SafePal.jpg'
import safepalwallet from './SafePalWallet.jpg'
import SparkPoint from './SparkPoint.jpg'
import Spatium from './Spatium.jpg'
import talkenwalet from './talkenwalet.jpg'
import tokenary from './tokenary.jpg'
import tokenpocket from './tokenpocket.jpg'
import tokenwallet from './tokenwallet.jpg'
import tonguewallet from './tonguewallet.jpg'
import torus from './torus.jpg'
import trustee from './trusteeWallet.jpg'
import trustVault from './trustVault.jpg'
import trustwallet from './trustwallet.jpg'
import twitter from './twitter-brands.svg'
import unstoppable from './unstoppableWallet.jpg'
import viawallet from './viawallet.jpg'
import vision from './vision.jpg'
import wallet from './wallet.jpg'
import walletio from './walletio.jpg'
import walletconnect from './walletconnect-header.png'
import xinfin from './xinfin.jpg'
import zelcore from './zelcore.jpg'


const image ={
 zelcore,xinfin,wallet,walletconnect,walletio,viawallet,vision,unstoppable,talkenwalet,tokenary,tokenpocket,
 tokenwallet,tonguewallet,torus,trustVault,trustee,trustwallet,twitter,safepalwallet,SparkPoint,Spatium,Rainbow,Rwallet,
 peakdefiwallet,plasmapay,Pillar,o3Wallet,onto,ownbit,mathwallet,meet,metamask,midas,morix,mykey,ledgerlive,
 logo,loopring,keyring,kyberswap,jadewallet,i,inchwallet,infinity,infinyo,halodefi,hashkeyme,huobiWallet,
 github,gnosis,gridplus,guardwallet,facebook,flarwalle,easypocket,eidoo,ellipal,equal,dcentwallet,defiant,dharna,
 dokwallet,coin98,coinbase,coinomi,coolwallet,cybavowallet,crypto,bash,binance,bitkeep,bitpay,bridgewallet,
 btc,aktion,alice,alphawallet,argent,atomic,atwallet,authereum
}
export default image